# Generated by Django 5.1.2 on 2024-11-16 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ormapp', '0002_bankloan_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankloan',
            name='Age',
        ),
    ]
