# Generated by Django 5.1.2 on 2024-11-16 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ormapp', '0003_remove_bankloan_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankloan',
            name='Age',
            field=models.IntegerField(default=18),
        ),
    ]
