# Generated by Django 5.1.2 on 2024-11-16 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ormapp', '0004_bankloan_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankloan',
            name='City',
            field=models.CharField(default='Chennai', max_length=20),
        ),
        migrations.AddField(
            model_name='bankloan',
            name='Gender',
            field=models.CharField(default='M', max_length=1),
        ),
    ]
